from django.urls import path
from . import views
urlpatterns=[
    path('',views.login),
    path('admin',views.admin),
    path('login',views.login),
    path('setmcq',views.setmcq),
    path('signup',views.signup),
    path('startexam',views.startexam),
    path('forgot_password',views.forgot_password),
    path('reset_password',views.reset_password),
    path('success_reset/<int:student_id>',views.success_reset,name='sucess_reset'),
    path('warning',views.warning),
    path('login1',views.login1),
    path('logout',views.logout),
    path('signup_code',views.signup_code),
    path('leaderboard',views.leaderboard),
    path('editexam',views.editexam),
    path('clear',views.clear),
    path('Add_question',views.Add_question),
    path('set_exam',views.set_exam),
    path('settheory_question',views.settheory_question),
    path('settheory/',views.settheory),
    path('course_input',views.course_input),
    path('year_input',views.year_input),
    path('sem_input',views.sem_input),
    path('theory_paper/<int:id>',views.theory_paper),
    path('set_mcq',views.set_mcq),
    path('mcq_paper/<int:course_id>',views.mcq_paper),
    path('check_mcq',views.check_mcq),
    path('sr/<int:id>/',views.sr, name='sr'),
    path('teacher',views.teacher),
    path('viewexam',views.viewexam),
    path('view_results/<int:student_id>',views.view_results),
    path('select_exam_type',views.select_exam_type),
    path('submit_answers/<int:id>', views.submit_answers),
    path('view_student_exam/<int:student_id>/', views.view_student_exam, name='view_student_exam'),
    path('success_page', views.success_page, name='success_page'),
    path('base',views.base),
    path('success_sign',views.success_sign),
    path('error',views.error,name='error'),
]