# Generated by Django 4.2.6 on 2024-08-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory_question',
            name='Answer_a',
        ),
        migrations.RemoveField(
            model_name='theory_question',
            name='Answer_b',
        ),
        migrations.CreateModel(
            name='Student_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_a', models.TextField(blank=True)),
                ('answer_b', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.student')),
                ('theory_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.theory_question')),
            ],
        ),
    ]
