# Generated by Django 4.2.6 on 2024-08-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_remove_theory_question_answer_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq_question',
            name='Course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='Semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='Year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.year'),
            preserve_default=False,
        ),
    ]
