# Generated by Django 4.2.6 on 2024-08-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_mcq_question_course_mcq_question_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.course')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.semester')),
                ('Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.year')),
            ],
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='course_offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.courseoffering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theory_question',
            name='course_offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.courseoffering'),
            preserve_default=False,
        ),
    ]
