# Generated by Django 4.2.6 on 2024-08-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_courseoffering_mcq_question_course_offering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_question',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='Year',
        ),
        migrations.RemoveField(
            model_name='theory_question',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='theory_question',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='theory_question',
            name='Year',
        ),
    ]
