# Generated by Django 4.2.6 on 2024-08-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_remove_mcq_question_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_question',
            name='course_offering',
        ),
        migrations.RemoveField(
            model_name='theory_question',
            name='course_offering',
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='Course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='Semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='Year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theory_question',
            name='Course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theory_question',
            name='Semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theory_question',
            name='Year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.year'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseOffering',
        ),
    ]
