# Generated by Django 4.2.7 on 2024-08-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_remove_mcq_question_course_offering_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_response',
            table='SR',
        ),
    ]
