# Generated by Django 4.2.6 on 2024-08-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_alter_student_response_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_response',
            old_name='answer_a',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='theory_question',
            old_name='Mark_a',
            new_name='Mark',
        ),
        migrations.RenameField(
            model_name='theory_question',
            old_name='Question_a',
            new_name='Question',
        ),
        migrations.RemoveField(
            model_name='student_response',
            name='answer_b',
        ),
        migrations.RemoveField(
            model_name='theory_question',
            name='Mark_b',
        ),
        migrations.RemoveField(
            model_name='theory_question',
            name='Question_b',
        ),
    ]
