# Generated by Django 4.2.6 on 2024-08-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_rename_answer_a_student_response_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_response',
            name='answer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
