# Generated by Django 4.2.6 on 2024-08-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0009_alter_student_response_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_response',
            name='student',
        ),
    ]
