# Generated by Django 4.2.6 on 2024-08-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0010_remove_student_response_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_response',
            name='answer',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
