# Generated by Django 4.2.6 on 2024-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0011_alter_student_response_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_response',
            name='answer',
            field=models.TextField(),
        ),
    ]
