# Generated by Django 4.2.6 on 2024-08-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0012_alter_student_response_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory_question',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student_Response',
        ),
    ]
