# Generated by Django 4.2.6 on 2024-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0013_theory_question_answer_delete_student_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory_question',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
