# Generated by Django 4.2.6 on 2024-08-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0015_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory_question',
            name='Obtained_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
