# Generated by Django 4.2.6 on 2024-08-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0017_pageannotation_alter_theory_question_obtained_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theory_question',
            old_name='Obtained_marks',
            new_name='ObtainedMarks',
        ),
    ]
