# Generated by Django 4.2.6 on 2024-08-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0018_rename_obtained_marks_theory_question_obtainedmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAnnotation',
        ),
    ]
