# Generated by Django 4.2.6 on 2024-08-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0019_delete_pageannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.student')),
                ('theory_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.theory_question')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.year')),
            ],
        ),
    ]
