# Generated by Django 4.2.6 on 2024-08-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0020_student_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_response',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student_response',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student_response',
            name='year',
        ),
        migrations.RemoveField(
            model_name='theory_question',
            name='answer',
        ),
        migrations.AddField(
            model_name='student_response',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
