# Generated by Django 4.2.6 on 2024-08-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0021_remove_student_response_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_response',
            name='student',
        ),
    ]
