# Generated by Django 4.2.6 on 2024-08-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0022_remove_student_response_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_response',
            name='Mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_response',
            name='Question',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
