# Generated by Django 4.2.6 on 2024-08-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0023_student_response_mark_student_response_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theory_question',
            name='ObtainedMarks',
        ),
        migrations.AddField(
            model_name='student_response',
            name='Obtained_Mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
