# Generated by Django 4.2.6 on 2024-08-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0024_remove_theory_question_obtainedmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_response',
            name='Obtained_Mark',
            field=models.TextField(blank=True),
        ),
    ]
