# Generated by Django 4.2.6 on 2024-08-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0025_alter_student_response_obtained_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_response',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.student'),
            preserve_default=False,
        ),
    ]
