# Generated by Django 4.2.6 on 2024-08-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0027_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
